### ISSUE TITLE
How does this compare to "jss" and/or "j2c"?

### ISSUE THREAD

**Issue by serapath** [kodyl/stilr#10]
[jss](https://github.com/jsstyles/jss)
[j2c](https://github.com/pygy/j2c)
[smart-css](https://github.com/hackhat/smart-css)

**Comment by chriskjaer** [comment]
Well, first of all Stilr is the only solution out there that uses a content hash to generate the class name for your styles. Which means that we get duplicate style removal out of the box and it solves the namespace clashing that CSS often suffers from. 

Besides that, Stilr tries to do one thing and do it well. It let's you create a bunch of styles and gives you a string of CSS when you render the stylesheet. What you do with that is up to you. Some prefer to mount it in the header before the app is rendered. Other outputs it to a css file in their build step. 
In one of our production builds right now, we render our styles on the server, run them through an autoprefixer based on the clients header (e.g. if the user uses IE9, we only apply prefixes for that browser) and attach that to the serverside rendered React view.

Since Stilr only gives you a CSS string, it doesn't solve autoprefixing or attaching stuff to the document for you, like jss, j2c or smartCSS does, but honestly... There's no reason to. Attaching a stylesheet to the DOM is so simple. e.g.
```
let stylesheet = document.createElement('style');
stylesheet.textContent = StyleSheet.render();
document.head.appendChild(stylesheet);
```
And autoprefixing is solved by using postCSS's autoprefixer.

There's probably other differences, but I haven't used any of them enough to tell that.
