### ISSUE TITLE
Multiple values using arrays?

### ISSUE THREAD

**Issue by nmn** [kodyl/stilr#4]
There is a similar project, called JSS (https://github.com/jsstyles/jss)
It has this great feature for dealing with the limitation of JS objects with unique keys:
https://github.com/jsstyles/jss#multiple-declarations-with-identical-property-names

I can't think of many situations where this would be useful when already using autoprefixr, but I think it would be a good feature to have to be feature complete.

Perhaps using JSS would make this simpler, but word of warning, JSS doesn't support features such as nested pseudo selectors and media queries etc.

**Comment by chriskjaer** [comment]
Yeah, I've seen their approach before and I'm not really a fan. The way they use arrays is just as a poor mans replacement for autoprefixer and I see no reason to implement that into Stilr core. If you really need a specific prefix, you can do something like `WebkitTransition: opacity .5s`

BUT. There is a use case for arrays as values. E.g some css properties allow for multiple values:

```javascript
const styles = StyleSheet.create({
  container: {
    boxShadow: [
      '1px 1px black',
      '0 0 10px tomato' 
    ],
    backgroundImage: [
      url('../images/main.png'),
      url('../images/avatar.png') no-repeat top left
    ]
  }
})
```

**Comment by nmn** [comment]
I think the real idea is not to have just prefixes, because that would create non-unique key names anyway. I think the main reason to support array values is usually to have fallback styles. Can't think of a great example but something like this:

```
background: rgb(255,0,0);
background: rgba(255,0,0,0.8);
```

Here the old browsers get an opaque red, but newer browsers get a translucent red.

**Comment by chriskjaer** [comment]
Yeah, I see your point about fallback styles. But I don't agree that it should be handled directly in Stilr. 
In my opinion, everything that's related to fallback values and prefixes should be handled in you build step and since Stilr just outputs plain old CSS, we have awesome tools like PostCSS post processors (https://github.com/postcss/postcss) that we can use.

In your case, I would just add https://github.com/postcss/postcss-color-rgba-fallback to the build step.

Do only reason prefixes is supported right now, is because I use the internal React inline style converter, and it supports prefixes. We that's removed, I'm considering removing prefix support all together and just add a warning in dev that prefixes should be handled in your build step.

**Comment by chriskjaer** [comment]
So when I was adding tests for this, I realised that this is how the react style helper is already handling arrays. (Like my solution).
